USE DataWarehouse;

CREATE TABLE bronze.ERP_CUST_AZ12 (
ERP_CID NVARCHAR(50),
ERP_BDATE DATE,
ERP_GEN CHAR(10)
);

CREATE TABLE bronze.ERP_LOC_A101 (
ERP_CID NVARCHAR(50),
ERP_CNTRY CHAR(50)
);

CREATE TABLE bronze.ERP_PX_CAT_G1V2 (
ERP_ID NVARCHAR(50),
ERP_CAT CHAR(50),
ERP_SUBCAT CHAR(50),
ERP_MAINTENANCE CHAR(50)
);