USE DataWarehouse;

IF OBJECT_ID ('bronze.CRM_CUST_INFO','U') IS NOT NULL
	DROP TABLE bronze.CRM_CUST_INFO
CREATE TABLE bronze.CRM_CUST_INFO (
CST_ID INT,
CST_KEY NVARCHAR(50),
CST_FIRSTNAME NVARCHAR(50),
CST_LASTNAME NVARCHAR(50),
CST_MARITAL_STATUS NVARCHAR(50),
CST_GENDER NVARCHAR(50),
CST_CREATE_DATE DATE
);

IF OBJECT_ID ('bronze.CRM_PRD_INFO','U') IS NOT NULL
	DROP TABLE bronze.CRM_PRD_INFO
CREATE TABLE bronze.CRM_PRD_INFO (
PRD_ID INT,
PRD_KEY NVARCHAR(50),
PRD_NAME NVARCHAR(50),
PRD_COST INT,
PRD_LINE CHAR(1),
PRD_START_DT DATETIME,
PRD_END_DT DATETIME
);

IF OBJECT_ID ('bronze.CRM_SALES_DETAILS','U') IS NOT NULL
	DROP TABLE bronze.CRM_SALES_DETAILS
CREATE TABLE bronze.CRM_SALES_DETAILS (
SLS_ORD_NUM NVARCHAR(50),
SLS_PRD_KEY NVARCHAR(50),
SLS_CUST_ID INT,
SLS_ORDER_DT INT,
SLS_SHIP_DT INT,
SLS_DUE_DT INT,
SLS_SALES INT,
SLS_QUANTITY INT,
SLS_PRICE INT
);