CREATE OR ALTER PROCEDURE bronze.LOAD_BRONZE AS
BEGIN
	BEGIN TRY
		DECLARE @START_TIME DATETIME, @END_TIME DATETIME;
		SET @START_TIME=GETDATE();
		TRUNCATE TABLE bronze.CRM_CUST_INFO;

		BULK INSERT bronze.CRM_CUST_INFO 
		FROM 'C:\Users\mayur\Documents\SQL-Data-Warehouse-Project\databases\source_crm\cust_info.csv'
		WITH(
			FIRSTROW=2,
			FIELDTERMINATOR=',',
			TABLOCK
		);
		SET @END_TIME=GETDATE();
		PRINT '>>LOAD DURATION:'+CAST(DATEDIFF(SECOND,@START_TIME,@END_TIME) AS NVARCHAR)+' SECONDS';

		SET @START_TIME=GETDATE();
		TRUNCATE TABLE bronze.CRM_PRD_INFO;

		BULK INSERT bronze.CRM_PRD_INFO
		FROM 'C:\Users\mayur\Documents\SQL-Data-Warehouse-Project\databases\source_crm\prd_info.csv'
		WITH(
			FIRSTROW=2,
			FIELDTERMINATOR=',',
			TABLOCK
		);
		SET @END_TIME=GETDATE();
		PRINT '>>LOAD DURATION:'+CAST(DATEDIFF(SECOND,@START_TIME,@END_TIME) AS NVARCHAR)+' SECONDS';

		SET @START_TIME=GETDATE();
		TRUNCATE TABLE bronze.CRM_SALES_DETAILS;

		BULK INSERT bronze.CRM_SALES_DETAILS
		FROM 'C:\Users\mayur\Documents\SQL-Data-Warehouse-Project\databases\source_crm\sales_details.csv'
		WITH(
			FIRSTROW=2,
			FIELDTERMINATOR=',',
			TABLOCK
		);
		SET @END_TIME=GETDATE();
		PRINT '>>LOAD DURATION:'+CAST(DATEDIFF(SECOND,@START_TIME,@END_TIME) AS NVARCHAR)+' SECONDS';

		SET @START_TIME=GETDATE();
		TRUNCATE TABLE bronze.ERP_CUST_AZ12;

		BULK INSERT bronze.ERP_CUST_AZ12
		FROM 'C:\Users\mayur\Documents\SQL-Data-Warehouse-Project\databases\source_erp\CUST_AZ12.csv'
		WITH(
			FIRSTROW=2,
			FIELDTERMINATOR=',',
			TABLOCK
		);
		SET @END_TIME=GETDATE();
		PRINT '>>LOAD DURATION:'+CAST(DATEDIFF(SECOND,@START_TIME,@END_TIME) AS NVARCHAR)+' SECONDS';

		SET @START_TIME=GETDATE();
		TRUNCATE TABLE bronze.ERP_LOC_A101;

		BULK INSERT bronze.ERP_LOC_A101
		FROM 'C:\Users\mayur\Documents\SQL-Data-Warehouse-Project\databases\source_erp\LOC_A101.csv'
		WITH(
			FIRSTROW=2,
			FIELDTERMINATOR=',',
			TABLOCK
		);
		SET @END_TIME=GETDATE();
		PRINT '>>LOAD DURATION:'+CAST(DATEDIFF(SECOND,@START_TIME,@END_TIME) AS NVARCHAR)+' SECONDS';

		SET @START_TIME=GETDATE();
		TRUNCATE TABLE bronze.ERP_PX_CAT_G1V2;

		BULK INSERT bronze.ERP_PX_CAT_G1V2
		FROM 'C:\Users\mayur\Documents\SQL-Data-Warehouse-Project\databases\source_erp\PX_CAT_G1V2.csv'
		WITH(
			FIRSTROW=2,
			FIELDTERMINATOR=',',
			TABLOCK
		);
		SET @END_TIME=GETDATE();
		PRINT '>>LOAD DURATION:'+CAST(DATEDIFF(SECOND,@START_TIME,@END_TIME) AS NVARCHAR)+' SECONDS';
	END TRY

	BEGIN CATCH
		PRINT '----------------------------ERORR OCCURED------------------------------'
		PRINT 'ERROR_MESSAGE'+ERROR_MESSAGE()
		PRINT 'ERROR_NUMBER'+ERROR_NUMBER()
	END CATCH
END